/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.csnakes.gdx.particle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
